### ISSUE TITLE
plz，When i use myself dataset there is an error

### ISSUE THREAD

**Issue by BJFU-CS2012** [lblaoke/TLC#7]
RuntimeError: mat1 and mat2 shapes cannot be multiplied (24x8192 and 2048x18)

**Comment by lblaoke** [comment]
If you're using another dataset, you should implement your own network architecture. The dimensions of features are determined by input image, and thus you cannot use the architecture designed for CIFAR or ImageNet directly on your dataset.

**Comment by BJFU-CS2012** [comment]
Thank you for your reply. I have modified my architecture before asking questions, but I still prompt this error. Today, I found that valid loaded in main.py during the step-by-step debugging -valid_data_loader-. The loader returns the default dataloader, and then I modify the loader here to my own and the program can be run.
