### ISSUE TITLE
Code to generate results in Table 3

### ISSUE THREAD

**Issue by Deepakgthomas** [lblaoke/TLC#9]
Hello, 

I enjoyed reading your paper and implementing your code. While running your code, I see that only results from Table 1 are shown. I am trying to reproduce your results. Therefore, could you share the code to generate your results in Table 3?

Please let me know if you have any questions or require additional clarification.

**Comment by lblaoke** [comment]
I lost the code for failure prediction, but they are simple to implement. The AUC and FHR-95 are based on `sklearn.metrics` and `scipy.interpolate` respectively, and the ECE is implemented as follows:
```
def _ece_score(y_true,y_pred,bins=10):
    ece = 0.
    for i in range(bins):
        c_start,c_end = i/bins,(i+1)/bins
        mask = (c_start<=y_pred)&(y_pred<c_end)
        ni = mask.count_nonzero().item()
        if ni==0:
            continue
        acc,conf = y_true[mask].sum()/ni,y_pred[mask].mean()
        ece += ni*(acc-conf).abs()
    return float(ece)/len(y_true)
```
They all use the uncertainty (or `confidence=1-uncertainty`) to predict the failures. The partition of class regions are the same as ACC. Hope this will help you!

**Comment by Deepakgthomas** [comment]
Thank you very much.
